apiVersion: v1
kind: Secret
metadata:
  name: <SECRET NAME>
data:
  # Value for httpasswd generated via `htpasswd -nb kubernaut clusterfun | base64`
  # When mounted in a Pod as a Volume, creates a file named `htpasswd` (the key name).
  htpasswd: a3ViZXJuYXV0OiRhcHIxJFVtdlFwNGpVJEM2aXJhQXpsQ2VKZ0tVeHFnb3o2NC8KCg==
