apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <DEPLOYMENT NAME>
spec:
  replicas: <NUMBER OF REPLICAS>
  template: 
    metadata:
      labels:
        <LABELS>
    spec:
      containers:
      - name: <CONTAINER NAME>
        image: <IMAGE NAME>
        ports:
        - containerPort: <CONTAINER PORT>
